version: '3.8'
services:
  caption-scraper:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caption-scraper
    volumes:
      - ./backend/captions:/app/captions
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173" 